/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PtlImageGallery {
        "activeImageRatio": number;
        "images": string[];
    }
    interface PtlImageSlider {
        "captions": string[];
        "images": string[];
        "minHeight": string;
    }
    interface PtlSearchInput {
        "apiUrl": string;
    }
    interface PtlSearchResult {
    }
    interface PtlWidgetProducts {
        "apiHost": string;
        "limitProducts": string;
        "widgetTitle": string;
    }
}
export interface PtlSearchInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPtlSearchInputElement;
}
declare global {
    interface HTMLPtlImageGalleryElement extends Components.PtlImageGallery, HTMLStencilElement {
    }
    var HTMLPtlImageGalleryElement: {
        prototype: HTMLPtlImageGalleryElement;
        new (): HTMLPtlImageGalleryElement;
    };
    interface HTMLPtlImageSliderElement extends Components.PtlImageSlider, HTMLStencilElement {
    }
    var HTMLPtlImageSliderElement: {
        prototype: HTMLPtlImageSliderElement;
        new (): HTMLPtlImageSliderElement;
    };
    interface HTMLPtlSearchInputElement extends Components.PtlSearchInput, HTMLStencilElement {
    }
    var HTMLPtlSearchInputElement: {
        prototype: HTMLPtlSearchInputElement;
        new (): HTMLPtlSearchInputElement;
    };
    interface HTMLPtlSearchResultElement extends Components.PtlSearchResult, HTMLStencilElement {
    }
    var HTMLPtlSearchResultElement: {
        prototype: HTMLPtlSearchResultElement;
        new (): HTMLPtlSearchResultElement;
    };
    interface HTMLPtlWidgetProductsElement extends Components.PtlWidgetProducts, HTMLStencilElement {
    }
    var HTMLPtlWidgetProductsElement: {
        prototype: HTMLPtlWidgetProductsElement;
        new (): HTMLPtlWidgetProductsElement;
    };
    interface HTMLElementTagNameMap {
        "ptl-image-gallery": HTMLPtlImageGalleryElement;
        "ptl-image-slider": HTMLPtlImageSliderElement;
        "ptl-search-input": HTMLPtlSearchInputElement;
        "ptl-search-result": HTMLPtlSearchResultElement;
        "ptl-widget-products": HTMLPtlWidgetProductsElement;
    }
}
declare namespace LocalJSX {
    interface PtlImageGallery {
        "activeImageRatio"?: number;
        "images"?: string[];
    }
    interface PtlImageSlider {
        "captions"?: string[];
        "images"?: string[];
        "minHeight"?: string;
    }
    interface PtlSearchInput {
        "apiUrl"?: string;
        "onFetchSearchApi"?: (event: PtlSearchInputCustomEvent<JSON>) => void;
    }
    interface PtlSearchResult {
    }
    interface PtlWidgetProducts {
        "apiHost"?: string;
        "limitProducts"?: string;
        "widgetTitle"?: string;
    }
    interface IntrinsicElements {
        "ptl-image-gallery": PtlImageGallery;
        "ptl-image-slider": PtlImageSlider;
        "ptl-search-input": PtlSearchInput;
        "ptl-search-result": PtlSearchResult;
        "ptl-widget-products": PtlWidgetProducts;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ptl-image-gallery": LocalJSX.PtlImageGallery & JSXBase.HTMLAttributes<HTMLPtlImageGalleryElement>;
            "ptl-image-slider": LocalJSX.PtlImageSlider & JSXBase.HTMLAttributes<HTMLPtlImageSliderElement>;
            "ptl-search-input": LocalJSX.PtlSearchInput & JSXBase.HTMLAttributes<HTMLPtlSearchInputElement>;
            "ptl-search-result": LocalJSX.PtlSearchResult & JSXBase.HTMLAttributes<HTMLPtlSearchResultElement>;
            "ptl-widget-products": LocalJSX.PtlWidgetProducts & JSXBase.HTMLAttributes<HTMLPtlWidgetProductsElement>;
        }
    }
}
